api_nose:
  stage: test
  image: python:3.6
  services:
      - name: jezsw/crumpit_mongo
      - name: jezsw/crumpit_sql
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - pytest
