language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - docker

before_install:
- docker pull jezsw/crumpit_mongo
- docker pull jezsw/crumpit_sql
- docker run -d -p 27017:27017 --rm jezsw/crumpit_mongo
- docker run -d -p 3306:3306 --rm jezsw/crumpit_sql
- sleep 30
- docker ps -a

# command to install dependencies
install:
- pip install -r requirements.txt
- pip install -e .

script:
- pytest --cov=crumpitmanagerapi --junitxml=report.xml
- coverage xml