language: python

python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

services:
  - docker

before_install:
- docker pull jezsw/crumpit_mongo
- docker run -p 3306:3306 --rm jezsw/crumpit_mongo
- docker run -p 27017:27017 --rm jezsw/crumpit_mongo
- docker ps -a

script:
- pytest --cov=crumpitmanagerapi --junitxml=report.xml
- coverage xml