logDir: '/var/log/CrumpitManagerLogs'
flask: {
  port: 5607
}
mongoDB: { 
  ip: '127.0.0.1',
  port: 27017
}
sqlDB: {
  ip: '127.0.0.1',
  port: 3306
}
clusterInfo: {
  gridIONS: [
    {
      name: 'grid1',
      IP: '127.0.0.1',
      mountLocation: '/mnt/gridX'
    }
  ],
  storageLocation: '/mnt/nanostore',
  remoteStorage: [
    {
      name: 'Location1',
      IP: '127.0.0.1',
      sshUsername: 'jez',
      backupOrder: 1,
      storageLocation: '/mnt/backup/Nanopore',
      logDir: '/var/log/CrumpitManagerLogs'
    }
  ]
}