logDir: '/var/log/CrumpitManagerLogs'
nanoporeOptions: {
  basecallerFile: '/home/jez/NanoporeServer/otherDev/crumpitmanagerAPIs/data/basecaller_workflows_20200220.txt',
  barcodeFile: '/home/jez/NanoporeServer/otherDev/crumpitmanagerAPIs/data/barcoder_kits_20200220.txt'
}
flask: {
  port: 5607
}
mongoDB: { 
  ip: '127.0.0.1',
  port: 27017
}
sqlDB: {
  ip: '127.0.0.1',
  port: 3306,
}
clusterInfo: {
  gridIONS: [
    {
      name: 'grid1',
      IP: '127.0.0.1',
      mountLocation: '/home/jez/NanoporeServer/gridX'
    },
    {
      name: 'grid2',
      IP: '127.0.0.1',
      mountLocation: '/home/jez/NanoporeServer/gridX'
    }
  ],
  storageLocation: '/home/jez/NanoporeServer/nanostore',
  remoteStorage: [
    {
      name: 'CS',
      IP: 'analysis1.mmmoxford.uk',
      port: 8081,
      sshUsername: 'jez@ndm.local',
      backupOrder: 1,
      storageLocation: '/mnt/microbio/Nanopore',
      logDir: '/var/log/RESCOMPBackupLogs/progress'
    },
    {
      name: 'RESCOMP',
      IP: 'rescomp.well.ox.ac.uk',
      sshUsername: 'jez',
      backupOrder: 2,
      storageLocation: '/arc/bag/mmmbackup/microbio/Nanopore',
      tunnelIP: 'dingo'
    }
  ]
}