logDir: '~/log/CSbackups/progress'
diskDir: '~/log/CSbackups/disk'
nanoporeOptions: {
  basecallerFile: 'data/basecaller_workflows_4.2.2.txt',
  barcodeFile: 'data/barcoder_kits_4.2.2.txt'
}
singImg: '~/images/crumpit_3-0.simg'
flask: {
  port: 5607
}
mongoDB: { 
  ip: '127.0.0.1',
  port: 27017
}
sqlDB: {
  ip: '127.0.0.1',
  port: 3306,
}
clusterInfo: {
  gridIONS: [
    {
      name: 'grid0',
      IP: '127.0.0.1',
      mountLocation: '~/grid0'
    },
  ],
  storageLocation: '~/nanostore',
  customRefsLocation: '~/nanostore/dbs/refseq/custom_refs',
  remoteStorage: [
  ]
}
