logDir: '/var/log/CSbackups/progress'
nanoporeOptions: {
  basecallerFile: '/home/mmmnano/crumpitmanagerAPIs/data/basecaller_workflows_4.2.2.txt',
  barcodeFile: '/home/mmmnano/crumpitmanagerAPIs/data/barcoder_kits_4.2.2.txt'
}
flask: {
  port: 5607
}
mongoDB: { 
  ip: '163.1.213.19',
  port: 27017
}
sqlDB: {
  ip: '163.1.213.19',
  port: 3306,
}
clusterInfo: {
  gridIONS: [
    {
      name: 'grid0',
      IP: '127.0.0.1',
      mountLocation: '/mnt/grid0'
    },
    {
      name: 'grid1',
      IP: '127.0.0.1',
      mountLocation: '/mnt/grid1'
    }
  ],
  storageLocation: '/mnt/nanostore',
  remoteStorage: [
    {
      name: 'CS',
      IP: 'analysis1.mmmoxford.uk',
      port: 8081,
      sshUsername: 'nick@ndm.local',
      backupOrder: 1,
      storageLocation: '/mnt/microbio/Nanopore',
      logDir: '/var/log/RESCOMPBackupLogs/progress'
    },
    {
      name: 'RESCOMP',
      IP: 'rescomp.well.ox.ac.uk',
      sshUsername: 'jez',
      backupOrder: 2,
      storageLocation: '/arc/bag/mmmbackup/microbio/Nanopore',
      tunnelIP: 'dingo'
    }
  ]
}
