{
  'logDir': {'type': 'string'},
  'flask': {'required': False, 'type' : 'dict',
    'schema': {
      'port': {'type': 'integer'}
    }
  },
  'mongoDB': {'required': False, 'type' : 'dict',
    'schema': {
      'ip': {'type': 'string'},
      'port': {'required': False, 'type': 'integer'}
    }
  }
}