{
  'logDir': {'type': 'string'},
  'diskDir': {'required': False, 'type': 'string'},
  'nanoporeOptions': {'required': False, 'type' : 'dict',
    'schema': {
      'basecallerFile': {'type': 'string'},
      'barcodeFile': {'type': 'string'}
    }
  },
  'flask': {'required': False, 'type' : 'dict',
    'schema': {
      'port': {'type': 'integer'}
    }
  },
  'mongoDB': {'required': False, 'type' : 'dict',
    'schema': {
      'ip': {'type': 'string'},
      'port': {'required': False, 'type': 'integer'}
    }
  },
  'sqlDB': {'required': False, 'type' : 'dict',
    'schema': {
      'ip': {'type': 'string'},
      'port': {'required': False, 'type': 'integer'},
      'database': {'required': False, 'type': 'string'}
    }
  },
  'clusterInfo': {
    'type': 'dict',
    'schema': {
      'gridIONS': {
        'type': 'list',
        'schema': { 
          'type': 'dict', 
          'schema': {
            'name': {'type': 'string'},
            'IP': {'type': 'string'},
            'mountLocation': {'type': 'string'}
          }
        }
      },
      'storageLocation': {'type': 'string'},
      'remoteStorage': {
        'required': False,
        'type': 'list',
        'schema': {
          'type': 'dict', 
          'schema': {
            'name': {'type': 'string'},
            'IP': {'type': 'string'},
            'port': {'required': False, 'type': 'integer'},
            'storageLocation': {'type': 'string'},
            'backupOrder': {'type': 'integer'},
            'logDir': {'required': False,'type': 'string'},
            'diskDir': {'required': False,'type': 'string'},
            'sshUsername': {'type': 'string'},
            'sshKey': {'required': False, 'type': 'string'},
            'tunnelIP': {'required': False, 'type': 'string'}
          }
        }
      }
    }
  }
}